name: reVC Linux x64 OpenGL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build zip \
            libopenal-dev libsndfile1-dev libmpg123-dev \
            libgl1-mesa-dev libx11-dev libxrandr-dev \
            libxinerama-dev libxcursor-dev libxi-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols \
            libwayland-bin libglew-dev

      - name: Configure
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DREVC_VENDORED_LIBRW=ON \
            -DREVC_AUDIO=OAL \
            -DREVC_WITH_DISCORD_RPC=OFF \
            -DLIBRW_PLATFORM=GL3 \
            -DLIBRW_GL3_GFXLIB=GLFW \
            -DREVC_INSTALL=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Package
        run: |
          mkdir -p package
          find build -type f -name reVC -exec cp {} package/reVC \;
          zip -j reVC-modmenu-linux-opengl-x64.zip package/reVC

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: reVC-modmenu-linux-opengl-x64
          path: reVC-modmenu-linux-opengl-x64.zip
          if-no-files-found: error
          retention-days: 30
